#!/bin/sh

if ! command -v pygmentize >/dev/null 2>&1; then
    echo >&2 "Error: You need pygmentize to compile the presentation"
    exit
fi

pdflatex solution-outline.tex
pdflatex --shell-escape presentation.tex
